sonar.projectKey=Upendra-23-cmd_Full-Stack-Microservice-Boilerplate-Go-React-PostgreSQL-Redis
sonar.organization=upendra-23-cmd

sonar.sources=frontend/src

sonar.exclusions=**/node_modules/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info