name: CI-backend-image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    defaults:
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Golang Enviroment
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Check code formatting
        run: go fmt ./...

      # - name: check linting error
      #   uses: golangci/golangci-lint-action@v8
      #   with:
      #     version: latest
      #     working-directory: ./backend
        
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: backend 
          args: >
            -Dsonar.projectKey=Upendra-23-cmd_Full-Stack-Microservice-Boilerplate-Go-React-PostgreSQL-Redis
            -Dsonar.organization=upendra-23-cmd
            -Dsonar.host.url=https://sonarcloud.io


      

      

      

        



