name: CI-buildandpush-image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-CI:
    runs-on: ubuntu-latest
    environment: SONAR_TOKEN
    permissions:
      contents: read
      packages: write 

    defaults:
      run: 
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # - name: Run eslint to check code quality
      #  # run: npm run lint

      - name: test the application
        run: npm run test:coverage
      
      - name: build the application
        run: npm run build

      - name: Debug Secrets
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            echo "length of SONAR_TOKEN: ${#SONAR_TOKEN}"
            if [ -z "$SONAR_TOKEN" ]; then
              echo "SONAR_TOKEN missing"
              exit 1
            fi
            echo "SONAR_TOKEN exists"

      - name: SonarQube code analysis
        uses: SonarSource/sonarqube-scan-action@v6
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: https://sonarcloud.io
        with:
          projectBaseDir: frontend 
    
      - name: login to github ghcr
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: build  docker image
        run: |
         REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
         echo "Using repo: $REPO"
         docker build \
         -t ghcr.io/${REPO}/frontend:${{ github.sha }} \
         -t ghcr.io/${REPO}/frontend:latest \
         .
    
      - name: push docker image
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO/frontend:${{ github.sha }}
          docker push ghcr.io/$REPO/frontend:latest
    
