name: CI-buildandpush-image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-CI:
    runs-on: ubuntu-latest
    environment: sonarqube

    defaults:
      run: 
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # - name: Run eslint to check code quality
      #  # run: npm run lint

      - name: test the application
        run: npm run test:coverage
      
      - name: build the application
        run: npm run build

      - name: Debug Secrets
        env:
            SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
            echo "length of SONARQUBE_TOKEN: ${#SONARQUBE_TOKEN}"
            if [ -z "$SONARQUBE_TOKEN" ]; then
              echo "SONARQUBE_TOKEN missing"
              exit 1
            fi
            echo "SONARQUBE_TOKEN exists"

      - name: SonarQube code analysis
        uses: SonarSource/sonarqube-scan-action@v6
        env:
         SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
         SONAR_HOST_URL: https://sonarcloud.io
    
      - name: login to github ghcr
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: build  docker image
        run: |
         docker build \
         -t ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} \
         -t ghcr.io/${{ github.repository }}/frontend:latest \
         .
    
      - name: push docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/frontend:latest
    